config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "games#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :games, only: %i[index new create show edit update destroy] do
    resources :bookings, only: %i[create]
    resources :reviews, only: %i[new create]
  end
  resources :bookings, only: %i[index]
  resources :categories, only: %i[index show]
  resources :reviews, only: %i[index]
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/views/shared/_all_cards.html.erb
<div>
  <div class="main-title">
    <h1>Games for Rental</h1>
    <div class = 'saber'></div>
  </div>

  <div class="button-add-container">
    <%= link_to '+ Add a new game listing', new_game_path, class: 'new-game-btn' %>
  </div>

  <div class="row">
    <div id="main-grid">
      <% @games.each_with_index do |game, index| %>
        <% class_name = ['left', 'center', 'right'][index % 3 ] %>
        <div class="card-games" style="background: #050e2d;">
          <div class="card_content">
            <div class="card_image">
              <img src="<%= cl_image_path game.photo.key %>" alt="<%= game.title %>" style="height: 500px; width: 100%;">
            </div>
            <div class="card_details">
              <h1 class="title"><%= game.title %></h1>
              <% if game.description.length > 400 %>
                <h2 class="subtitle"><%= game.description.first(400)%>......</h2>
              <% else %>
                <h2 class="subtitle"><%= game.description.first(400)%></h2>
              <% end %>
            </div>
            <div class="card_footer">
              <p class="subtitle">Price: <%= game.price %></p>
              <%= button_to game_path(game), class: 'play-button', method: :get do %>
                PLAY
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_all_reviews.html.erb
<h1 class= 'reviews-header'>Game Reviews</h1>
<div class = 'saber'></div>
<div class='reviews'>
  <% unless @reviews == [] %>
  <div class = 'reviews-grid'>
    <% @reviews.each do |review| %>
      <div class = 'grid-item'>
        <h3>From <%= review.user.first_name %>:</h3>
        <p><%= review.content %> (rating: <%= review.rating %>)</p>
      </div>
    <% end %>
    </div>
  <% else %>
    <h3>No reviews have been submitted</h3>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <div class="share">
    <button class="btn3">
        <svg height="30px" width="30px" viewBox="0 0 30 30" xmlns="http://www.w3.org/2000/svg" class="git">    <path d="M15,3C8.373,3,3,8.373,3,15c0,5.623,3.872,10.328,9.092,11.63C12.036,26.468,12,26.28,12,26.047v-2.051 c-0.487,0-1.303,0-1.508,0c-0.821,0-1.551-0.353-1.905-1.009c-0.393-0.729-0.461-1.844-1.435-2.526 c-0.289-0.227-0.069-0.486,0.264-0.451c0.615,0.174,1.125,0.596,1.605,1.222c0.478,0.627,0.703,0.769,1.596,0.769 c0.433,0,1.081-0.025,1.691-0.121c0.328-0.833,0.895-1.6,1.588-1.962c-3.996-0.411-5.903-2.399-5.903-5.098 c0-1.162,0.495-2.286,1.336-3.233C9.053,10.647,8.706,8.73,9.435,8c1.798,0,2.885,1.166,3.146,1.481C13.477,9.174,14.461,9,15.495,9 c1.036,0,2.024,0.174,2.922,0.483C18.675,9.17,19.763,8,21.565,8c0.732,0.731,0.381,2.656,0.102,3.594 c0.836,0.945,1.328,2.066,1.328,3.226c0,2.697-1.904,4.684-5.894,5.097C18.199,20.49,19,22.1,19,23.313v2.734 c0,0.104-0.023,0.179-0.035,0.268C23.641,24.676,27,20.236,27,15C27,8.373,21.627,3,15,3z"></path></svg>
        <span class="tooltiptext3">
          <div class="card">
            <%= image_tag "https://avatars.githubusercontent.com/u/25823874?v=4" %>
          </div>
          <div class="username"><a href="https://github.com/estebanhuwel">@esteban</a></div>
        </span>
      </button>
      <button class="btn3">
        <svg height="30px" width="30px" viewBox="0 0 30 30" xmlns="http://www.w3.org/2000/svg" class="git">    <path d="M15,3C8.373,3,3,8.373,3,15c0,5.623,3.872,10.328,9.092,11.63C12.036,26.468,12,26.28,12,26.047v-2.051 c-0.487,0-1.303,0-1.508,0c-0.821,0-1.551-0.353-1.905-1.009c-0.393-0.729-0.461-1.844-1.435-2.526 c-0.289-0.227-0.069-0.486,0.264-0.451c0.615,0.174,1.125,0.596,1.605,1.222c0.478,0.627,0.703,0.769,1.596,0.769 c0.433,0,1.081-0.025,1.691-0.121c0.328-0.833,0.895-1.6,1.588-1.962c-3.996-0.411-5.903-2.399-5.903-5.098 c0-1.162,0.495-2.286,1.336-3.233C9.053,10.647,8.706,8.73,9.435,8c1.798,0,2.885,1.166,3.146,1.481C13.477,9.174,14.461,9,15.495,9 c1.036,0,2.024,0.174,2.922,0.483C18.675,9.17,19.763,8,21.565,8c0.732,0.731,0.381,2.656,0.102,3.594 c0.836,0.945,1.328,2.066,1.328,3.226c0,2.697-1.904,4.684-5.894,5.097C18.199,20.49,19,22.1,19,23.313v2.734 c0,0.104-0.023,0.179-0.035,0.268C23.641,24.676,27,20.236,27,15C27,8.373,21.627,3,15,3z"></path></svg>
        <span class="tooltiptext3">
          <div class="card">
            <%= image_tag "https://avatars.githubusercontent.com/u/115866158?v=4" %>
          </div>
          <div class="username"><a href="https://github.com/thiseas16">@thiseas16</a></div>
        </span>
      </button>
      <button class="btn3">
        <svg height="30px" width="30px" viewBox="0 0 30 30" xmlns="http://www.w3.org/2000/svg" class="git">    <path d="M15,3C8.373,3,3,8.373,3,15c0,5.623,3.872,10.328,9.092,11.63C12.036,26.468,12,26.28,12,26.047v-2.051 c-0.487,0-1.303,0-1.508,0c-0.821,0-1.551-0.353-1.905-1.009c-0.393-0.729-0.461-1.844-1.435-2.526 c-0.289-0.227-0.069-0.486,0.264-0.451c0.615,0.174,1.125,0.596,1.605,1.222c0.478,0.627,0.703,0.769,1.596,0.769 c0.433,0,1.081-0.025,1.691-0.121c0.328-0.833,0.895-1.6,1.588-1.962c-3.996-0.411-5.903-2.399-5.903-5.098 c0-1.162,0.495-2.286,1.336-3.233C9.053,10.647,8.706,8.73,9.435,8c1.798,0,2.885,1.166,3.146,1.481C13.477,9.174,14.461,9,15.495,9 c1.036,0,2.024,0.174,2.922,0.483C18.675,9.17,19.763,8,21.565,8c0.732,0.731,0.381,2.656,0.102,3.594 c0.836,0.945,1.328,2.066,1.328,3.226c0,2.697-1.904,4.684-5.894,5.097C18.199,20.49,19,22.1,19,23.313v2.734 c0,0.104-0.023,0.179-0.035,0.268C23.641,24.676,27,20.236,27,15C27,8.373,21.627,3,15,3z"></path></svg>
        <span class="tooltiptext3">
          <div class="card">
            <%= image_tag "https://avatars.githubusercontent.com/u/51957583?v=4"%>
          </div>
          <div class="username"><a href="https://github.com/Vancz123">@Vancz123</a></div>
        </span>
      </button>
    </div>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div style= 'display: flex; justify-content: space-between;'>
        <ul class="navbar-nav me-auto">
          <%= link_to root_path do %>
            <div class = 'logo'>
              <%= image_tag "https://res.cloudinary.com/dnorlz2hl/image/upload/v1677679919/production/logo_pifx6l.png", class: 'logo' %>
              <h4>GameBnB</h4>
            </div>
          <% end %>
          <%= link_to 'All Games', games_path  %>
          <%= link_to 'Categories', categories_path  %>
          <%= link_to 'Contact', contact_path %>
          <%= link_to 'About', about_path %>
        </ul>
      </div>
    </div>
    <div style = 'display:flex; width: 25%; align-items: center; margin-right: 10px;'>
      <div class = 'search-form'>
        <%= form_with url: games_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a game"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <% if @current_user.photo.key? %>
          <%= cl_image_tag @current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "https://media.istockphoto.com/id/1332100919/vector/man-icon-black-icon-person-symbol.jpg?s=612x612&w=0&k=20&c=AVVJkvxQQCuBhawHrUhDRTCeNQ3Jgt0K1tXjJsFy1eg=", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "My Reviews", reviews_path, class: "dropdown-item" %>
          <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
          <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
        </div>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      <% end %>
    </div>
</div>

app/views/shared/test.html.erb
<div class="topnav">
  <%= link_to 'Home', root_path  %>
  <%= link_to 'All Games', games_path  %>
  <%= link_to 'Categories', categories_path  %>
  <a href="#contact">Contact</a>
  <a href="#about">About</a>
  <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %>
  <input type ="text" name ="searchbox" class="search" placeholder ="Search for Games">
</div>