config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "games#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :games, only: %i[index new create show edit update destroy] do
    resources :bookings, only: %i[create]
    resources :reviews, only: %i[new create]
  end
  resources :bookings, only: %i[index]
  resources :categories, only: %i[index show]
  resources :reviews, only: %i[index]
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :photo
  has_many :game_categories
  has_many :categories, through: :game_categories
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, except: %i[home index show]
  before_action :set_current_user
  before_action :set_game, only: %i[show update edit]
  before_action :check_if_booked, only: %i[show]


  def home
    authorize Game
  end

  def index
    if params[:query].present?
      sql_query = "title ILIKE :query OR description ILIKE :query"
      @games = policy_scope(Game).where(sql_query, query: "%#{params[:query]}%")
    else
      @games = policy_scope(Game).all
    end
  end

  def new
    @game = Game.new
    authorize @game
  end

  def create
    @game = Game.new(game_params)

    @game.user = current_user
    if @game.save
      params[:game][:categories].each_with_index do |category, i|
        if i != 0
          category = Category.find(category)
          GameCategory.create(game: @game, category: category)
        end
      end
      redirect_to game_path(@game) # later to be changed in game_path(@game) when we have a show
    else
      render :new, status: :unprocessable_entity
    end
    authorize @game
  end

  def show
    @bookings = Booking.all
    @booking = Booking.new(game: @game)
    @reviews = @game.reviews
    authorize @game
  end

  def edit
    authorize @game
  end

  def update
    if @game.update(game_params)
      redirect_to game_path(@game)
    else
      render :new, status: :unprocessable_entity
    end
    authorize @game
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
    authorize @game
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:price, :title, :description, :photo)
  end

  def set_current_user
    @current_user = current_user
  end

  def check_if_booked
    booked = false
    if @current_user
      @current_user.bookings.each do |booking|
        booked = true if booking.game == @game
      end
    end
    @booked = booked
  end
end

app/views/games/edit.html.erb
<h1>Edit game listing</h1>
<%= simple_form_for [@game] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/games/home.html.erb
<div class="home">
<%# <div class="welcome-container">
  <div class="loader"></div>
  <h1 class="main-title">Welcome to GamesBnB</h1>
  <div class="loader"></div>
</div> %>

  <!-- banner-->
  <div class="banner">
    <div class="bg">
      <div class="content">
        <div class="loader" style= 'margin-top: 25px;'></div>
        <h2>A new Home for<br>Game Lovers</h2>
        <div class="loader"></div>
        <p class="slogan">Play More, Spend Less with Game Rentals. </p>
        <%= link_to 'Join Now',  new_user_registration_path, class: 'btn' %>
      </div>
      <%# <img src="https://i.pinimg.com/1200x/81/b2/a9/81b2a9f518e78535242c1b4a5d41d146.jpg"> %>
    </div>
  </div>
  </div>

  <!--about-->
  <div class="about">
    <div class="contentBx">
      <h2>About Us</h2>
      <div class="loader"></div>
      <p>Thiseas, Esteban, and Gabriel are three young developers from different parts of the world, brought together by their shared passion for gaming and technology.</p>
      <p>Thiseas, hailing from the beautiful country of Greece, is the team's front-end developer, responsible for designing and creating the user interface of their web page.</p>
      <p>Esteban, from Argentina, is the team's back-end developer, responsible for building the web page's infrastructure and ensuring it runs smoothly.</p>
      <p>Finally, Gabriel, from Portugal, is the team's full-stack developer, bringing both front-end and back-end skills to the table and ensuring that their web page is well-rounded and efficient.</P>
      <P>Together, they work tirelessly to create the best web page for renting games, incorporating their diverse backgrounds and experiences into every aspect of the site.</p>
      <p>With their combined expertise, Thiseas, Esteban, and Gabriel are poised to take the gaming world by storm.</p>
    </div>
    <img src="https://cdn.dribbble.com/users/1129235/screenshots/16793661/media/aeb3e50c3b14a2504305fb8f8fa3dd1b.gif" alt="">
  </div>

<%# <iframe width="560" height="315" src="https://www.youtube.com/embed/FFfdyV8gnWk?autoplay=1" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> %>

app/views/games/index.html.erb
<div style="display:flex">
 <%= render "shared/all_cards" %>
</div>

app/views/games/new.html.erb
<div style = "display: flex; align-items: center; justify-content: center; height: 100vh;">
  <div>
    <h1>New game listing</h1>
    <%= simple_form_for [@game] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :categories, as: :check_boxes, collection: Category.all, label_method: :name, value_method: :id %>
      <%= f.input :photo, as: :file %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class='page-container'>
    <div class="game-banner" style="
          background-image: linear-gradient(to bottom, rgb(0, 0, 0), rgba(0, 0, 0, 0)),
          url('<%= cl_image_path @game.photo.key, fetch_format: :auto, crop: :fill %>')"
        >
        <%= link_to 'Back to games', games_path, class: 'btn-back btn', 'data-controller': "sticky", 'data-action': "scroll@window->sticky#stick", 'data-sticky-target': "button" if request.path.match(/\/games\/\d/) %>
        <div class='game-title'>
          <h1><%= @game.title %></h1>
        </div>
    </div>
  <div class = 'center'>
    <div class='game-wrapper'>
        <div class="game-container">
          <div class = 'game-header'>
            <h1>About this Game</h1>
          </div>
          <div class = 'saber'></div>
          <div class="game-information">
            <p><%= @game.description %></p>
            <p><% @game.categories.each do |category| %>
              <%= link_to category.name, category_path(category), class: 'btn btn-light' %>
            <% end %>
            <div class="game-links">
              <%= link_to 'Edit', edit_game_path(@game), class: 'btn-edit btn btn-primary' if policy(@game).edit?%>
              <%= link_to 'Delete', game_path(@game), class: 'btn-delete btn btn-danger',
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } if policy(@game).edit? %>
            </div>
            </p>
            Price per day: <%= @game.price %>
          </div>
        </div>
        <div class="game-reviews">
          <%= render 'shared/all_reviews' %>
          <div class = 'review-button'>
            <%= link_to "Write a Review", new_game_review_path(@game), class: 'btn btn-info' if @booked%>
          </div>
        </div>
        <div class = 'booking-wrapper'>
          <h1 class = 'bookings-header'>Book it now</h1>
          <div class = 'saber'></div>
          <div class="booking">
            <%= render partial: 'bookings/form', locals: { bookings: @bookings, booking: @booking, current_user: @current_user } %>
            <div class="calendar">
              <%= render partial: 'bookings/calendar', locals: { bookings: @bookings, game: @game, current_user: @current_user} %>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>