config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "games#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :games, only: %i[index new create show edit update destroy] do
    resources :bookings, only: %i[create]
    resources :reviews, only: %i[new create]
  end
  resources :bookings, only: %i[index]
  resources :categories, only: %i[index show]
  resources :reviews, only: %i[index]
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :game_categories
  has_many :games, through: :game_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = policy_scope(Category)
  end

  def show
    @category = Category.find(params[:id])
    @games = Game.joins(:categories).where(categories: { name: @category.name })
    authorize @category
    authorize @games
  end
end

app/views/categories/index.html.erb
<div class="main-categories">
  <div class="sub-category-container">
    <% @categories.each do |category| %>
      <div class="button-container">
        <button data-text="Awesome" class="button-universe">
          <span class="actual-text">&nbsp;<%= link_to category.name, category_path(category)%>&nbsp;</span>
          <span class="hover-text" aria-hidden="true">&nbsp;<%= link_to category.name, category_path(category)%>&nbsp;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class = 'categories-page-container'>
  <div class="main-title title-container">
    <h1 ><%= @category.name %></h1>
    <div class = 'saber'></div>
  </div>

  <div class="button-add-container">
      <%= link_to 'Back to categories', categories_path,  class: 'new-game-btn' %>
      <%= link_to '+ Add a new game listing', new_game_path, class: 'new-game-btn' %>
  </div>

  <div class="row">
      <div id="main-grid">
        <% @games.each_with_index do |game, index| %>
          <% class_name = ['left', 'center', 'right'][index % 3 ] %>
          <div class="card-games" style="background: #050e2d;">
            <div class="card_content">
              <div class="card_image">
                <img src="<%= cl_image_path game.photo.key %>" alt="<%= game.title %>" style="height: 500px; width: 100%;">
              </div>
              <div class="card_details">
                <h1 class="title"><%= game.title %></h1>
                <% if game.description.length > 400 %>
                  <h2 class="subtitle"><%= game.description.first(400)%>......</h2>
                <% else %>
                  <h2 class="subtitle"><%= game.description.first(400)%></h2>
                <% end %>
              </div>
              <div class="card_footer">
                <p class="subtitle">Price: <%= game.price %></p>
                <%= button_to game_path(game), class: 'play-button', method: :get do %>
                  PLAY
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>